name: Trivy scan

on:
  push:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps: 

    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t python-image:v${{ github.run_number}} . 

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: python-image:v${{ github.run_number}}
        severity: HIGH, CRITICAL
        exit-code: '0' #test pour voir si la pipeline fonctionnne. Normalement 0
      